cc_library(
	name = "map",
	srcs  = ["map/helloWorld.cpp"],
	hdrs  = ["map/helloWorld.h"],
	visibility = ["//main:__pkg__"],
		

)
cc_library(
        name = "searchMethods",           
        srcs = ["searchMethods/bfs.cpp"],
        visibility = ["//main:__pkg__"],
                
)   
